#!/usr/bin/env ruby

require "mysqlexport"
require "mysqlexport/cli/cli"
require "mysqlexport/cli/help_parser"

cli = Mysqlexport::Cli.new

cli.parse_options
options = cli.config

Mysqlexport::HelpParser.new.parse(cli.options) if options[:help] == true
Mysqlexport::HelpParser.new.info if options == {}

to = options[:to] || "csv"
to = to.to_s.downcase
case to
when "csv"
  Mysqlexport::Csv.new(options).to_path
when "json"
  begin
    json_engine = options[:json_engine] || ""
    require json_engine
  rescue LoadError
    puts "[WARNING]: Invalid or no json engine provided using default engine"
  end
  Mysqlexport::Json.new(options).to_path
else
  raise Mysqlexport::Error, "invalid option [--to] only csv/json is allowed"
end
