name: Rubocop

on: [push,pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Rubocop 
      run: |
        bundle install
        bundle exec rake rubocop
